@startuml
robust "Event notifier" as EventNotifier
robust "RX" as RX
robust "RX UI" as RxUi
robust "UI state" as UiState
robust "Watchdog timer" as Timer

EventNotifier is processing
RX is OFF
RxUi is OFF
Timer is Idle
UiState is Off

@0
EventNotifier is processing
RX is OFF
RxUi is OFF


@20
EventNotifier -> RX : sig
RX is ON
RxUi is ON
UiState is OnHold
Timer is active

@40
EventNotifier -> RX : sig
RX is OFF
RxUi is ON
UiState is OnHoldOffReq

@120
RxUi is OFF
Timer -> UiState : to
UiState is OffHold

@160
Timer -> UiState : to
UiState is Off
Timer is Idle

@200
EventNotifier -> RX : sig
RX is ON
RxUi is ON
UiState is OnHold
Timer is active

@220
EventNotifier -> RX : sig
RX is ON

@240
EventNotifier -> RX : sig
RX is ON

@260
EventNotifier -> RX : sig
RX is ON

@280
EventNotifier -> RX : sig
RX is ON

@300
EventNotifier -> RX : sig
RX is OFF
RxUi is OFF
UiState is OffHold

@340
Timer -> UiState : to
UiState is Off
Timer is Idle

@400
EventNotifier -> RX : sig
RX is ON
RxUi is ON
UiState is OnHold
Timer is active

@420
EventNotifier -> RX : sig
RX is OFF
UiState is OnHoldOffReq

@440
EventNotifier -> RX : sig
RX is OFF

@460
EventNotifier -> RX : sig
RX is OFF

@480
EventNotifier -> RX : sig
RX is OFF

@500
EventNotifier -> RX : sig
RX is OFF
RxUi is OFF
UiState is OffHold

@540
Timer -> UiState : to
UiState is Off
Timer is Idle

@600
EventNotifier -> RX : sig
RX is ON
RxUi is ON
UiState is OnHold
Timer is active

@620
EventNotifier -> RX : sig
RX is OFF
UiState is OnHoldOffReq

@640
EventNotifier -> RX : sig
RX is ON
UiState is OnHold

@660
EventNotifier -> RX : sig
RX is OFF
UiState is OnHoldOffReq

@680
EventNotifier -> RX : sig
RX is ON
UiState is OnHold

@700
EventNotifier -> RX : sig
RX is OFF
RxUi is OFF
UiState is OffHold

@720
EventNotifier -> RX : sig
RX is ON
UiState is OffHoldOnReq

@740
EventNotifier -> RX : sig
RX is OFF
UiState is Off
Timer is Idle

@760
RxUi is OFF

@enduml
