@startuml
robust "Event notifier" as EventNotifier
robust "RX" as RX
robust "Current RX" as CurrentRX
robust "RX Timer" as RXTimer

EventNotifier is processing
RX is OFF
CurrentRX is OFF
RXTimer is Idle

@0
EventNotifier is processing
CurrentRX is OFF
RX is OFF
RXTimer is Idle

@20
EventNotifier -> RX : sig
RX is ON
CurrentRX is ON
RXTimer is active

@40
EventNotifier -> RX : sig
RX is OFF
CurrentRX is ON
RXTimer is active

@100
RX is OFF
RXTimer -> CurrentRX : to
CurrentRX is OFF
RXTimer is Idle

@120
EventNotifier -> RX : sig
RX is ON
CurrentRX is ON
RXTimer is active

@140
EventNotifier -> RX : sig
RX is OFF
CurrentRX is ON
RXTimer is active

@160
EventNotifier -> RX : sig
RX is OFF
CurrentRX is ON
RXTimer is active

@200
RX is OFF
RXTimer -> CurrentRX : to
CurrentRX is OFF
RXTimer is Idle

@220
EventNotifier -> RX : sig
RX is ON
CurrentRX is ON
RXTimer is active

@240
EventNotifier -> RX : sig
RX is ON
CurrentRX is ON
RXTimer is active

@300
RXTimer -> CurrentRX : to
CurrentRX is OFF
RXTimer is Idle

@320
EventNotifier -> RX : sig
RX is OFF

@enduml
