@startuml

!include Mdt/SerialPort/PortInfo.puml

namespace Mdt.SerialPort {

  class Handle {
    + bool isValid()
    + nativeHandle()
    + {static} fromNativeHandle()
  }

  class BasicSerialPort {
    + Handle open(PortInfo pi)
    + tryOpen(PortInfo pi)
  }

  BasicSerialPort ..> Handle
  BasicSerialPort ..> PortInfo

}

hide Mdt.SerialPort.PortInfo members
hide QSerialPortInfo members

@enduml
