@startuml
!include libusb/libusb_device_descriptor.puml

class libusb_endpoint_descriptor {
}

class libusb_interface_descriptor {
}

class libusb_interface {
}

class libusb_config_descriptor {
}

class libusb_container_id_descriptor {
}

class libusb_platform_descriptor {
}

@enduml
