@startuml
!include libusb/libusb_device_descriptor.puml
!include libusb/libusb_config_descriptor.puml
!include libusb/libusb_interface_descriptor.puml
!include libusb/libusb_endpoint_descriptor.puml


class libusb_container_id_descriptor {
}

class libusb_platform_descriptor {
}

@enduml
