@startuml
!include Mdt/SerialPort/PinoutSignals.puml
!include Mdt/SerialPort/PinoutSignalsEventNotifier.puml
!include Mdt/SerialPort/PinoutSignalsUiController.puml
!include Mdt/SerialPort/PinoutSignalsWidget.puml



hide QObject methods
hide QWidget methods
hide QPaintDevice
hide QIODeviceBase
hide QSerialPortInfo

@enduml
