@startuml
!include Mdt/SerialPort/SettingsEditor.puml
!include Mdt/SerialPort/TestSettingsEditor.puml

hide Mdt.SerialPort.PortInfo members
hide Mdt.SerialPort.TestLib.TestPortInfo members
hide Mdt.SerialPort.AbstractPortInfoListTableModel members
hide Mdt.SerialPort.PortInfoListTableModel members
hide Mdt.SerialPort.TestLib.TestPortInfoListTableModel members

@enduml
