@startuml
!include libusb/libusb.puml


namespace Mdt.Usb {

  class DeviceDescriptor {
  }

  class DeviceList {
  }

  DeviceList *--> "*" DeviceDescriptor

}

Mdt.Usb.DeviceDescriptor --> libusb_device


@enduml
