@startuml
!include libusb/libusb_config_descriptor.puml
!include Mdt/Usb/InterfaceDescriptor.puml

namespace Mdt.Usb {

  class ConfigDescriptor {
  }

  ConfigDescriptor *--> "*" Interface
}

Mdt.Usb.ConfigDescriptor *--> libusb_config_descriptor

@enduml
