!include Mdt/SerialPort/PortInfo.puml

namespace Mdt.SerialPort {

  class AbstractPortInfoListTableModel {
     {abstract} -doFetchAvailablePorts()
  }

  AbstractPortInfoListTableModel *--> "*" PortInfo

}
