!include Mdt/SerialPort/Settings.puml

namespace Mdt.SerialPort {

  class AbstractSettingsEditor {
    +Settings buildSettings()
    {abstract} -doFetchAvailablePorts()
  }

  AbstractSettingsEditor ..> Settings

}
