!include Mdt/SerialPort/SendByteByByteSettings.puml
!include Mdt/SerialPort/PortInfo.puml

namespace Mdt.SerialPort {

  class Settings {

  }

  Settings *--> SendByteByByteSettings
  Settings *--> PortInfo

}
