@startuml
!include Mdt/SerialPort/Settings.puml
!include Mdt/SerialPort/SettingsRawData.puml
!include Mdt/SerialPort/SettingsValidation.puml

namespace Mdt.SerialPort {

  class SettingsBuilder {
  }

  SettingsBuilder ..> Settings
  SettingsBuilder ..> SettingsRawData
  SettingsBuilder ..> SettingsValidation

}

@enduml
