@startuml
!include Mdt/SerialPort/Settings.puml
!include Mdt/SerialPort/SettingsRawData.puml

class SettingsValidation {
}

SettingsValidation ..> Settings
SettingsValidation ..> SettingsRawData

@enduml
