!include Mdt/SerialPort/AbstractSettingsEditor.puml
!include Mdt/SerialPort/TestLib/TestPortInfoListTableModel.puml

class TestSettingsEditor {
  -doFetchAvailablePorts()
}

Mdt.SerialPort.AbstractSettingsEditor <|-- TestSettingsEditor
TestSettingsEditor *--> Mdt.SerialPort.TestLib.TestPortInfoListTableModel
