@startuml
!include Mdt/SerialPort/ByteByByteWriter.puml

namespace Mdt.SerialPort.TestLib {

  class TestByteByByteWriter {
  }

}

Mdt.SerialPort.AbstractByteByByteWriter <|-- Mdt.SerialPort.TestLib.TestByteByByteWriter

@enduml
