!include Mdt/SerialPort/AbstractPortInfoListTableModel.puml
!include Mdt/SerialPort/TestLib/TestPortInfo.puml

namespace Mdt.SerialPort.TestLib {

  class TestPortInfoListTableModel {
    -doFetchAvailablePorts()
  }

  TestPortInfoListTableModel ..> TestPortInfo

  Mdt.SerialPort.AbstractPortInfoListTableModel <|-- TestPortInfoListTableModel
}
